# Generated by Django 5.0.6 on 2024-06-07 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
        ('locations_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='companies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies_api.company'),
            preserve_default=False,
        ),
    ]
