# Generated by Django 5.0.6 on 2024-06-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_api', '0002_location_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='companies',
            new_name='institutions',
        ),
    ]
