# Generated by Django 5.0.6 on 2024-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
        ('locations_api', '0003_rename_companies_location_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='institutions',
        ),
        migrations.AddField(
            model_name='location',
            name='companies',
            field=models.ManyToManyField(related_name='locations', to='companies_api.company'),
        ),
    ]
