"""
Django settings for django_rest_api project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-um62^ezw099r%=#-hybhjrt1^e03_s*bn!@xt@fu04%m=q15m&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#This is giving permission to HOSTS - The first element in the list here is our EC2 Instance Public IPv4 address (Hosting our online public deployed version of our project) and the second element is our localhost (NOTE: If we use the actual string 'localhost' it does not work, so we need to type the number version of our localhost URL --> Only way to successfuly run server locally after adding our EC2 address)
ALLOWED_HOSTS = [
    '3.17.166.207', 
    '127.0.0.1'
    ]


# Application definition
    #We MUST append/add our APP(s) in this list AND any packages/dependecies we installed to the Virtual Environment 

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'companies_api',
    'locations_api',
    'contacts_api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#For the CORS package (which allows for data fetches from domains/ports that are DIFFERENT from the domain/port of our API) we MUST also append it to the MIDDLEWARE list
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# To properly enable CORS, we MUST set it to True --> Here, we are indicating True to allow access/incoming requests from ALL/ANY origins (domains/ports)
    #We can test this out in Postman by creating a Header with the key set to 'Origin' and any Domain name as the value --> The response Headers should come back with this Header:  Access-Control-Allow-Origin = *
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'django_rest_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_rest_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_api'
        # 'USER': 'christopherjimenez',
        # 'PASSWORD': 'cratose@41795',
        # 'HOST': '127.0.0.1',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
