# Generated by Django 5.0.6 on 2024-06-06 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
