# Generated by Django 5.0.6 on 2024-06-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_api', '0002_contact_date_created'),
        ('locations_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations_api.location'),
            preserve_default=False,
        ),
    ]
